#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         3
bspc config window_gap          12

bspc config normal_border_color     "#393939"
bspc config focused_border_color    "#42be65"
bspc config presel_feedback_color   "#ee5396"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale /home/anon/Pictures/Wallpapers/dino.jpg &
pgrep -x polybar > /dev/null || polybar &

