[font]
size = 11.94

[font.normal]
family = "BlexMono Nerd Font"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "nvim\r"
key = "n"
mods = "Control"

[[keyboard.bindings]]
chars = "fg\r"
key = "z"
mods = "Control"

[window]
dynamic_padding = true

[window.padding]
x = 8
y = 8

[general]
import = ["/home/anon/.config/alacritty/oxocarbon-dark.toml"]
# import = ["/home/anon/.config/alacritty/oxocarbon-light.toml"]

